#!/usr/bin/env ruby

name, type = ARGV[0..1]
outfile = "optionals/#{name.downcase}.go"

methods = ARGV[2..-1] || []

require 'erb'

template = ERB.new(File.read("optionals/template.go.erb"))
contents = template.result(binding)

File.open(outfile, 'w+') do |f|
  f.write(contents)

  methods.each do |msg|
    template = ERB.new(File.read("optionals/method.go.erb"))
    contents = template.result(binding)
    f.write(contents)
  end
end

